### ISSUE TITLE
Getting error when trying to upload big file using js upload helper

### ISSUE THREAD

**Issue by matsola** [datocms/js-datocms-client#45]
Here's the program:
```

const SiteClient = require('datocms-client').SiteClient;
const dato = new SiteClient("YOUR APIKEY");

dato.uploadFile('<path to a file larger than 10MB>')
    .then(x => console.log(x));

```
Results in

```
(node:28475) UnhandledPromiseRejectionWarning: Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (/Users/mats-ola.persson/Work/yadayada/node_modules/follow-redirects/index.js:97:24)
    at RedirectableRequest.end (/Users/mats-ola.persson/Work/yadayada/node_modules/follow-redirects/index.js:116:8)
    at dispatchHttpRequest (/Users/mats-ola.persson/Work/yadayada/node_modules/axios/lib/adapters/http.js:272:11)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/mats-ola.persson/Work/yadayada/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/Users/mats-ola.persson/Work/yadayada/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by matjack1** [comment]
yes, I can confirm this bug, we'll work on it as soon as possible, sorry

**Comment by matjack1** [comment]
@matsola just to let you know, it's on master, I'll try getting a version out soon

**Comment by matjack1** [comment]
OK, done v2.0.8 has the limit raised to 100MB

**Comment by matsola** [comment]
Confirmed that it's working (however see https://github.com/datocms/js-datocms-client/pull/46).
