### ISSUE TITLE
Error in downloading and creating media during wp-import

### ISSUE THREAD

**Issue by eppemela** [datocms/js-datocms-client#47]
Hi guys, I was migrating a WP website to Dato and I encountered this issue with the media gallery files. Seems like the script tries to download the media objects by using only their relative path (i.e.  `/wp-content/uploads/2017/10/031c3b66-8693-35ac-a766-397dc4b0c898.jpg` instead of `https://www.wp-site-url.tld/wp-content/uploads/2017/10/031c3b66-8693-35ac-a766-397dc4b0c898.jpg`)

This is the error it throws after the "Fetching media" phase. 

```
Cannot import: /wp-content/uploads/2017/10/031c3b66-8693-35ac-a766-397dc4b0c898.jpg
Error: ENOENT: no such file or directory, access '/wp-content/uploads/2017/10/031c3b66-8693-35ac-a766-397dc4b0c898.jpg'
    at Object.accessSync (fs.js:206:3)
    at node (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/lib/upload/adapters/node.js:26:15)
    at Proxy.uploadFile (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/lib/upload/uploadFile.js:10:10)
    at _callee$ (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/lib/wpImport/import/media.js:71:47)
    at tryCatch (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/node_modules/regenerator-runtime/runtime.js:117:21)
    at asyncGeneratorStep (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/lib/wpImport/import/media.js:12:103)
    at _next (/Users/notmymac/Documents/workspace/wp-website/js-datocms-client/lib/wpImport/import/media.js:14:194)
    at /Users/notmymac/Documents/workspace/wp-website/js-datocms-client/lib/wpImport/import/media.js:14:364 {
  errno: -2,
  syscall: 'access',
  code: 'ENOENT',
  path: '/wp-content/uploads/2017/10/031c3b66-8693-35ac-a766-397dc4b0c898.jpg'
}
```

I managed to overcome the issue locally by overwriting the `mediaItemUrl` const in media.js file like this: 

```
const mediaItemUrl = `https://www.wp-site-url.tld${mediaItem.source_url};` 
```

Originally it was: `const mediaItemUrl = mediaItem.source_url;`

Cheers!

**Comment by matjack1** [comment]
hey @eppemela :)

I'm not sure if the bug is related to your WP installation or to our code.

I just checked another install and in the `source_url` I could see the entire URL.

If you want me to look more into the problem I would need to have a look at your site. You can share it also over support@datocms.com

Ciao!

**Comment by eppemela** [comment]
Ciao Mat, I suspected that... this site has many plugins activated. Nevermind, I'll close the issue! Thanks anyway, ciao!
