### ISSUE TITLE
`SiteClient#uploadFile(imageUrl)` throws TypeError: Cannot read property 'relationships' of undefined

### ISSUE THREAD

**Issue by mccallofthewild** [datocms/js-datocms-client#53]
`SiteClient#uploadFile(imageUrl)` throws `TypeError: Cannot read property 'relationships' of undefined` unexpectedly with normal usage.

The code previously worked, then randomly stopped functioning, both server-side and locally.

Setup: 
* Unix
* Node.js (v8, v9, v12)
* `datocms-client` version "2.0.10"
* Read/Write token 
* Core Plan 

The documented example fails:
```javascript
await cmsClient.uploadFile('http://i.giphy.com/NXOF5rlaSXdAc.gif');
```

Full error output: 
```javascript
    TypeError: Cannot read property 'relationships' of undefined
        at findInfoForProperty (<dir>/node_modules/datocms-client/lib/utils/findInfoForProperty.js:18:49)
        at jsonSchemaRelationships (<dir>/node_modules/datocms-client/lib/utils/jsonSchemaRelationships.js:29:58)
        at deserializeJsonApi (<dir>/node_modules/datocms-client/lib/utils/deserializeJsonApi.js:120:64)
        at deserialize (<dir>/node_modules/datocms-client/lib/utils/generateClient.js:114:80)
        at <dir>/node_modules/datocms-client/lib/utils/generateClient.js:125:28
        at run (<dir>/node_modules/core-js/modules/es6.promise.js:75:22)
        at <dir>/node_modules/core-js/modules/es6.promise.js:92:30
        at flush (<dir>/node_modules/core-js/modules/_microtask.js:18:9)
        at process._tickCallback (internal/process/next_tick.js:61:11)
```

Edit: Images are uploading successfully, but the method seems to throw an error while processing the response, so the resulting image ID isn't returned

**Comment by mccallofthewild** [comment]
This issue was caused by an old package version, likely related to a lack of backward compatibility with the server API.

Updating `datocms-client` to the latest version (currently v3.0.6) solved the issue.

**Comment by matjack1** [comment]
yes @mccallofthewild it's as you said, we had to break backwards compatibility and if you are working with file uploads you need to update the client, sorry for that
